import { ArrowRight, CheckCircle2, Clock3, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, Navigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { Button } from '../components/ui/button';
import { Logo } from '../components/layout/Logo';
import { ThemeToggle } from '../components/shared/ThemeToggle';

export function LandingPage(): JSX.Element {
  const { user, loading } = useAuth();
  if (!loading && user) return <Navigate to="/scheduled" replace />;
  return (
    <main className="min-h-screen overflow-hidden bg-white text-slate-900 dark:bg-slate-950 dark:text-white">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Logo /><div className="flex items-center gap-2"><ThemeToggle /><Link to="/login"><Button variant="ghost">Log in</Button></Link><Link to="/login"><Button>Get started <ArrowRight className="ml-2" size={16} /></Button></Link></div></nav>
      <section className="relative mx-auto grid max-w-7xl gap-12 px-6 pb-24 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-28">
        <div className="absolute -left-36 top-20 -z-0 h-80 w-80 rounded-full bg-emerald-100 blur-3xl dark:bg-emerald-950" />
        <div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-medium text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-300"><Sparkles size={16} /> Scheduling that respects your inbox</span><h1 className="mt-7 text-5xl font-semibold tracking-tight sm:text-6xl">Send thoughtfully.<br /><span className="text-emerald-500">On your schedule.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-500">ReachInbox is a focused outbound scheduler: write one thoughtful message, choose your pace, and let a persistent queue deliver each email at the right moment.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/login"><Button className="h-12 px-6">Schedule your first email <ArrowRight className="ml-2" size={18} /></Button></Link><a href="#how-it-works"><Button variant="outline" className="h-12 px-6">See how it works</Button></a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500">{['Real Google OAuth', 'Ethereal test sending', 'Redis-persisted schedules'].map((item) => <span className="flex items-center gap-2" key={item}><CheckCircle2 size={16} className="text-emerald-500" />{item}</span>)}</div></div>
        <div className="relative rounded-[2rem] border border-slate-200 bg-slate-50 p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="rounded-[1.4rem] bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex items-center justify-between"><span className="font-black tracking-tight">ONB</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-medium text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">Queue healthy</span></div><div className="mt-8 space-y-3">{['Product launch follow-up', 'A note for Sarah Wilson', 'Your onboarding checklist'].map((subject, index) => <div className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 dark:border-slate-800" key={subject}><div className="rounded-lg bg-emerald-100 p-2 text-emerald-600 dark:bg-emerald-950"><Mail size={17} /></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{subject}</p><p className="text-xs text-slate-400">To: contact{index + 1}@example.com</p></div><span className="flex items-center gap-1 rounded-full bg-orange-100 px-2 py-1 text-xs text-orange-600"><Clock3 size={12} /> {index + 1}:00 PM</span></div>)}</div></div></div>
      </section>
      <section id="how-it-works" className="border-y border-slate-100 bg-slate-50 py-20 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto max-w-7xl px-6"><p className="text-sm font-semibold uppercase tracking-widest text-emerald-600">Designed for reliable sending</p><h2 className="mt-3 text-3xl font-semibold">A small, deliberate delivery system.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[[Clock3, 'Choose the pace', 'Stagger emails and cap each sender’s hourly volume.'], [ShieldCheck, 'Keep the schedule', 'BullMQ, Redis AOF, and PostgreSQL retain future sends through restarts.'], [Mail, 'See every send', 'Review scheduled, deferred, sent, and failed messages in one calm dashboard.']].map(([Icon, title, text]) => { const FeatureIcon = Icon as typeof Clock3; return <div key={title as string} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-700 dark:bg-slate-950"><FeatureIcon className="text-emerald-500" /><h3 className="mt-5 text-lg font-semibold">{title as string}</h3><p className="mt-2 text-slate-500">{text as string}</p></div>; })}</div></div></section>
    </main>
  );
}
